/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import gradle.utilities.TextFormatter;
import org.apache.commons.lang3.StringUtils;
import org.example.list.LinkedList;

import static org.example.utilities.StringUtils.join;
import static org.example.utilities.StringUtils.split;
import static org.example.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {

    public static void main(String[] args) {

        String text = "Hello, World!";

        String reversed = StringUtils.reverse(text);

        System.out.println(reversed);

        System.out.println(TextFormatter.addPrefix(reversed));

    }

}